server:
  port: 8080

reqpart:
  api:
    get: https://httpbin.org/get
    post: https://httpbin.org/post

respart:
  api:
    json: http://openapi.seoul.go.kr:8088/sample/json/GetParkInfo/1/5/
    xml: http://openapi.seoul.go.kr:8088/sample/xml/GetParkInfo/1/5/